"""phase0_initial_schema

Revision ID: 5d7105cb28a9
Revises: 
Create Date: 2026-07-26 17:51:58.467184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = '5d7105cb28a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handlers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='姓名'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='电话'),
    sa.Column('role', sa.Enum('HANDLER', 'MANAGER', 'RESEARCHER', 'ADMIN', name='user_role'), nullable=False, comment='角色'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handlers_email'), 'handlers', ['email'], unique=True)
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='模型名称'),
    sa.Column('version', sa.String(length=32), nullable=False, comment='语义版本号'),
    sa.Column('type', sa.Enum('POSE', 'BEHAVIOR', 'SCORING', name='model_type'), nullable=False),
    sa.Column('framework', sa.Enum('PYTORCH', 'ONNX', 'TENSORRT', name='model_framework'), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False, comment='相对 models_dir 的路径'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否为当前激活版本'),
    sa.Column('metrics_json', sa.JSON(), nullable=True, comment='性能指标（mAP/精度/延迟等）'),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_is_active'), 'ml_models', ['is_active'], unique=False)
    op.create_index(op.f('ix_ml_models_type'), 'ml_models', ['type'], unique=False)
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='犬名'),
    sa.Column('breed', sa.String(length=64), nullable=True, comment='品种（马犬/昆明犬/德牧等）'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='出生日期'),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='dog_gender'), nullable=True),
    sa.Column('chip_id', sa.String(length=64), nullable=True, comment='芯片号'),
    sa.Column('handler_id', sa.Integer(), nullable=True),
    sa.Column('training_stage', sa.Enum('P0', 'P1', 'P2', name='training_stage'), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handler_id'], ['handlers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dogs_chip_id'), 'dogs', ['chip_id'], unique=True)
    op.create_index(op.f('ix_dogs_handler_id'), 'dogs', ['handler_id'], unique=False)
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=True),
    sa.Column('session_date', sa.DateTime(timezone=True), nullable=False, comment='训练时间'),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('standard', sa.Enum('GA_T', 'USPCA', 'FCI_IGP', 'CUSTOM', name='scoring_standard'), nullable=False, comment='评分标准'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['handler_id'], ['handlers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_dog_id'), 'training_sessions', ['dog_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_handler_id'), 'training_sessions', ['handler_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('handler_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False, comment='相对 upload_dir 的路径'),
    sa.Column('storage_filename', sa.String(length=128), nullable=False, comment='存储文件名（uuid + 扩展名）'),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', name='video_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['handler_id'], ['handlers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_dog_id'), 'videos', ['dog_id'], unique=False)
    op.create_index(op.f('ix_videos_handler_id'), 'videos', ['handler_id'], unique=False)
    op.create_index(op.f('ix_videos_session_id'), 'videos', ['session_id'], unique=False)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    op.create_table('behaviors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('behavior_class', sa.Enum('SIT', 'DOWN', 'STAND', 'WALK', 'RUN', 'JUMP', 'LIE_SIDE', 'CRAWL', 'HEEL', 'COME', 'RETRIEVE', 'RELEASE', 'GUARD', 'BARK', 'QUIET', 'SEARCH', 'BITE', 'OUT', 'DEFEND', 'TRACK', 'SCALE', 'OBSTACLE', name='behavior_class'), nullable=False, comment='行为类别'),
    sa.Column('detector', sa.Enum('RULE', 'POSEC3D', 'STGCN_BC', name='behavior_detector'), nullable=False, comment='检测器'),
    sa.Column('start_frame', sa.Integer(), nullable=False),
    sa.Column('end_frame', sa.Integer(), nullable=False),
    sa.Column('start_sec', sa.Float(), nullable=False),
    sa.Column('end_sec', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behaviors_behavior_class'), 'behaviors', ['behavior_class'], unique=False)
    op.create_index(op.f('ix_behaviors_video_id'), 'behaviors', ['video_id'], unique=False)
    op.create_table('keypoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('frame_idx', sa.Integer(), nullable=False, comment='帧序号'),
    sa.Column('frame_time_sec', sa.Float(), nullable=False, comment='帧时间（秒）'),
    sa.Column('keypoints_json', sa.JSON(), nullable=False, comment='24 个 [x, y, confidence]'),
    sa.Column('detection_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keypoints_video_id'), 'keypoints', ['video_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('standard', sa.Enum('GA_T', 'USPCA', 'FCI_IGP', 'CUSTOM', name='scoring_standard'), nullable=False, comment='评分标准'),
    sa.Column('accuracy', sa.Float(), nullable=False, comment='动作准确度'),
    sa.Column('response_latency', sa.Float(), nullable=True, comment='响应延迟（Phase 2）'),
    sa.Column('duration', sa.Float(), nullable=False, comment='保持时长'),
    sa.Column('search_efficiency', sa.Float(), nullable=True, comment='搜索效率（Phase 2）'),
    sa.Column('attention', sa.Float(), nullable=False, comment='注意力'),
    sa.Column('courage', sa.Float(), nullable=True, comment='胆量欲望（Phase 3）'),
    sa.Column('gait_quality', sa.Float(), nullable=True, comment='步态质量（Phase 3）'),
    sa.Column('overall', sa.Float(), nullable=False, comment='综合分'),
    sa.Column('scoring_engine_version', sa.String(length=32), nullable=False, comment='评分引擎版本'),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_video_id'), 'scores', ['video_id'], unique=False)
    op.create_table('behavior_vectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('behavior_id', sa.Integer(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False, comment='向量维度'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=False, comment='行为嵌入向量'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_vectors_behavior_id'), 'behavior_vectors', ['behavior_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behavior_vectors_behavior_id'), table_name='behavior_vectors')
    op.drop_table('behavior_vectors')
    op.drop_index(op.f('ix_scores_video_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_keypoints_video_id'), table_name='keypoints')
    op.drop_table('keypoints')
    op.drop_index(op.f('ix_behaviors_video_id'), table_name='behaviors')
    op.drop_index(op.f('ix_behaviors_behavior_class'), table_name='behaviors')
    op.drop_table('behaviors')
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_session_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_handler_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_dog_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_training_sessions_handler_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_dog_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_dogs_handler_id'), table_name='dogs')
    op.drop_index(op.f('ix_dogs_chip_id'), table_name='dogs')
    op.drop_table('dogs')
    op.drop_index(op.f('ix_ml_models_type'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_is_active'), table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_handlers_email'), table_name='handlers')
    op.drop_table('handlers')
    # ### end Alembic commands ###
